stajproje2/Controllers/GüncellemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using stajproje2.Models;

namespace stajproje2.Controllers
{
    public class GüncellemeController : Controller
    {
        Model1 db = new Model1();

       
        public ActionResult Güncelleperso(int id)
        {
            var perso = db.Kullanıcı.Find(id);
            
            return View(perso);

        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Güncelleperso(Kullanıcı k)
        {
            var b=db.Kullanıcı.Where(x=>x.k_mail==k.k_mail);
            var a = b.Count();
            if (a>0)
            {
                ViewBag.uyarı = "Bu eposta sistemde kayıtlı";
                return View(k);
            }
            else
            {
                var perso = db.Kullanıcı.Find(k.k_id);
                if (ModelState.IsValid)
                {
                    perso.k_islem_tarihi = DateTime.Now;
                    perso.k_isim = k.k_isim;
                    perso.k_tel = k.k_tel;
                    perso.k_mail = k.k_mail;
                    perso.k_baslangıc = k.k_baslangıc;
                    db.SaveChanges();
                    return RedirectToAction("Index", "Adimn");
                }
               
            }
            return View(k);  
            
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Güncellemust(int id)
        {
            var update = db.Musteri.Find(id);
            ViewBag.mst = id;
            return View(update);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Güncellemust(Musteri data)
        {
            var must = db.Musteri.Find(data.m_id);
            if (ModelState.IsValid)
            {
                must.m_ad = data.m_ad;
                must.m_tel = data.m_tel;
                must.m_mail = data.m_mail;
                must.m_sirket = data.m_sirket;
                db.SaveChanges();
                return RedirectToAction("Musteri", "Adimn");
            }
            return View(data);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Güncellesube(int id)
        {
            var sube = db.Subeler.Find(id);
            return View(sube);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Güncellesube(Subeler sub)
        {
            var sun = db.Subeler.Find(sub.sube_id);

            if (ModelState.IsValid)
            {
                sun.sube_ad = sub.sube_ad;
                sun.sube_il = sub.sube_il;
                sun.sube_tel = sub.sube_tel;
                sun.sube_adres = sub.sube_adres;
                db.SaveChanges();
                return RedirectToAction("Sube", "Adimn");
            }

            return View(sub);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Detay(int id)
        {
            var personel = new SelectList(db.Kullanıcı.ToList(), "k_id", "k_isim");
            ViewBag.user_id = personel;

            var musteri = new SelectList(db.Musteri.ToList(), "m_id", "m_ad");
            ViewBag.m_fk_id = musteri;

            var detay = db.Satıs.Find(id);
            return View(detay);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Detay(Satıs satıs)
        {
            var personel = new SelectList(db.Kullanıcı.ToList(), "k_id", "k_isim");
            ViewBag.user_id = personel;


            var musteri = new SelectList(db.Musteri.ToList(), "m_id", "m_ad");
            ViewBag.m_fk_id = musteri;

            var detay = db.Satıs.Find(satıs.sat_id);
            return View(satıs);
        }





        [Authorize(Roles = "User")]
        [HttpGet]
        public ActionResult Detaygetir(int id)
        {
            var personel = new SelectList(db.Kullanıcı.ToList(), "k_id", "k_isim");
            ViewBag.user_id = personel;

            var musteri = new SelectList(db.Musteri.ToList(), "m_id", "m_ad");
            ViewBag.m_fk_id = musteri;

            var detay = db.Satıs.Find(id);
            return View(detay);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public ActionResult Detaygetir(Satıs satıs)
        {
            var personel = new SelectList(db.Kullanıcı.ToList(), "k_id", "k_isim");
            ViewBag.user_id = personel;


            var musteri = new SelectList(db.Musteri.ToList(), "m_id", "m_ad");
            ViewBag.m_fk_id = musteri;

            var detay = db.Satıs.Find(satıs.sat_id);
            if (ModelState.IsValid)
            {
                detay.sat_adet = satıs.sat_adet;
                detay.sat_urun = satıs.sat_urun;
                detay.sat_fiyat = satıs.sat_fiyat;
                db.SaveChanges();
                return RedirectToAction("Satıs", "Adimn");
            }
            return View(satıs);
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Ziyraetata()
        {
            var personel = new SelectList(db.Kullanıcı.Where(x => x.k_Rol == "user").ToList(), "k_id", "k_isim");
            ViewBag.z_user_id = personel;

            var sube = new SelectList(db.Subeler.ToList(), "sube_id", "sube_ad");
            ViewBag.sube_fk_id = sube;
            
           
            


            return View();

        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Ziyraetata(Ziyaretler zet, Mail model)
        {
            var personel = new SelectList(db.Kullanıcı.Where(x=> x.k_Rol == "user").ToList(), "k_id", "k_isim");
            ViewBag.z_user_id = personel;

          

            var sube = new SelectList(db.Subeler.ToList(), "sube_id", "sube_ad");
            
            ViewBag.sube_fk_id = sube;
            zet.z_islem_tarihi = DateTime.Now;
            
             zet.z_olusturma = DateTime.Now;
             zet.z_olay_id = 5;
             db.Ziyaretler.Add(zet);
             db.SaveChanges();
               
            
            var perso = db.Kullanıcı.Where(k => k.k_id == zet.z_user_id).SingleOrDefault();
            var ziyare = db.Subeler.Where(x => x.sube_id == zet.sube_fk_id).SingleOrDefault();
            try
            {
                //Configuring webMail class to send emails  
                //gmail smtp server  
                WebMail.SmtpServer = "smtp.gmail.com";
                //gmail port to send emails  
                WebMail.SmtpPort = 587;
                WebMail.SmtpUseDefaultCredentials = true;
                //sending emails with secure protocol  
                WebMail.EnableSsl = true;
                //EmailId used to send emails from application  
                WebMail.UserName = "gss48081@gmail.com";
                WebMail.Password = "xyrrslfttwxlthew";
                Mail mai = new Mail();
              
                //Send email  
                WebMail.Send(to:perso.k_mail, subject: "Ziyaret Atandı", body:"Sayın "+perso.k_isim+ " "+" yöneticiniz"+" "+ziyare.sube_ad +" "+"şubesine " + zet.z_tarih + " "+ "tarihli ziyaret atadı.", cc: "gss48081@gmail.com", isBodyHtml: true);
                ViewBag.Status = "Email Sent Successfully.";
            }
            catch (Exception)
            {
                ViewBag.Status = "Problem while sending email, Please check details.";

            }

            return RedirectToAction("Ziyaret", "Adimn",zet);
        }

        public ActionResult ZiyaretIslemleri(int id)

        {
            var ziya = db.Ziyaretler.Find(id);
            // var personel = new SelectList(db.Kullanıcı.Where(x => x.k_Rol == "user").ToList(), "k_id", "k_isim");
            //ViewBag.z_user_id = personel;
            List<SelectListItem> deger1 = (from i in db.Kullanıcı.Where(x => x.k_Rol == "user").ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.k_isim,
                                               Value = i.k_id.ToString()
                                           }).ToList();
            ViewBag.ktgr = deger1;
            List<SelectListItem> sube = (from i in db.Subeler.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.sube_ad,
                                               Value = i.sube_id.ToString(),
                                              
                                               
                                           }).ToList();
            ViewBag.sube = sube;


            //var sube = new SelectList(db.Subeler.ToList(), "sube_id", "sube_ad");
            //ViewBag.sube_fk_id = sube;

            List<SelectListItem> ol = (from i in db.Olay.ToList()
                                       select new SelectListItem
                                       {
                                           Text = i.olay_islem,
                                           Value = i.olay_id.ToString()
                                       }).ToList();
            ViewBag.olay = ol;

            return View(ziya);
        }

        [HttpPost]
        public ActionResult ZiyaretIslemleri(Ziyaretler zet)
        {
            var ziya = db.Ziyaretler.Find(zet.z_id);
            List<SelectListItem> deger1 = (from i in db.Kullanıcı.Where(x => x.k_Rol == "user").ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.k_isim,

stajproje2/Views/Güncelleme/Detay.cshtml
@model stajproje2.Models.Satıs
@{
    ViewBag.Title = "Detay";
}

<h2>Detaygetir</h2>

@using (Html.BeginForm("Detaygetir", "Güncelleme", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="from-group">

       
        @Html.TextBoxFor(sat => sat.sat_urun, new { @class = "form-control" })
        <br />
        <label>Satılan Adet</label>
        @Html.TextBoxFor(sat => sat.sat_adet, new { @class = "form-control" })
        <br />

        bbbbbbbbbbb
    
        <label>Personel İsmi</label>
        @Html.TextAreaFor(sat => sat.Kullanıcı.k_isim, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })


        <label>Musteri İsmi </label>
        @Html.TextAreaFor(sat => sat.Musteri.m_ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(Model => Model.m_fk_id, "", new { @class = "text-danger" })

        <br />


        <label>Toplam Fiyat</label>

        @{
            int toplam = Convert.ToInt32(Model.sat_adet) * Convert.ToInt32(Model.sat_fiyat);
        }

        <input type="text" class="form-control" value="@toplam" />

        <br />

    </div>
    <br />
    <div>

        <a href="/Adimn/Satıs" class="btn btn-info">Geri Dön</a>
    </div>
}

stajproje2/Views/Güncelleme/Detaygetir.cshtml
@model stajproje2.Models.Satıs
@{
    ViewBag.Title = "Detaygetir";
}

<h2>Detaygetir</h2>

@using (Html.BeginForm("Detaygetir", "Güncelleme", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="from-group">

        <label>Satıs Id</label>
        @Html.TextBoxFor(sat => sat.sat_id, new { @class = "form-control" })
        <hr />
        <label>Satılan Urun</label>
        @Html.TextBoxFor(sat => sat.sat_urun, new { @class = "form-control" })
        <br />
        <label>Satılan Adet</label>
        @Html.TextBoxFor(sat => sat.sat_adet, new { @class = "form-control" })
        <br />

        <label>Satılan Fiyat</label>
        @Html.TextBoxFor(sat => sat.sat_fiyat, new { @class = "form-control" })
        <br />

        <label>Musteri İsmi </label>
        @Html.DropDownList("m_fk_id", null, "", htmlAttributes: new { @class = "form-control", })
        @Html.ValidationMessageFor(Model => Model.m_fk_id, "", new { @class = "text-danger" })
        <br />

        <label>Personel İsmi</label>
        @Html.DropDownList("user_id", null, "", htmlAttributes: new { @class = "form-control", })
        @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
        <br />


        <label>Toplam Fiyat</label>

        @{
            int toplam = Convert.ToInt32(Model.sat_adet) * Convert.ToInt32(Model.sat_fiyat);
        }

        <input type="text" class="form-control" value="@toplam" />

        <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
    <br />
    <div>

        <a href="/Adimn/Satıs" class="btn btn-info">Geri Dön</a>
    </div>
}

stajproje2/Views/Güncelleme/Güncellemust.cshtml
@model stajproje2.Models.Musteri
@{
    ViewBag.Title = "Musterigetir";
}

<h2>Musterigetir</h2>
@using (Html.BeginForm("Güncellemust", "Güncelleme", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="from-group">
        <label>Musteri Id</label>
        @Html.TextBoxFor(m => m.m_id, new { @class = "form-control" })

        <hr />
        <label>Musteri Ad</label>
        @Html.TextBoxFor(m => m.m_ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.m_ad, "", new { @class = "text-danger" })

        <hr />
        <label>Musteri Tel</label>
        @Html.TextBoxFor(m => m.m_tel, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.m_tel, "", new { @class = "text-danger" })



        <hr />
        <label>Musteri Mail</label>
        @Html.TextBoxFor(m => m.m_mail, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.m_mail, "", new { @class = "text-danger" })
        <hr />

        <label>Musteri Sirjet</label>
        @Html.TextBoxFor(m => m.m_sirket, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.m_sirket, "", new { @class = "text-danger" })
        <hr />

    </div>

    <div>

        <button class="btn btn-primary">Güncelle</button>
        <a href="/Adimn/Musteri/" class="btn btn-primary" style="margin-left:10px">Geri Don</a>
    </div>
}

stajproje2/Views/Güncelleme/Güncelleperso.cshtml
@model stajproje2.Models.Kullanıcı
@{
    ViewBag.Title = "Personelgetir";
}

<h2>Personelgetir</h2>
@using (Html.BeginForm("Güncelleperso", "Güncelleme", FormMethod.Post))
{
    @Html.AntiForgeryToken()
<div class="from-group">

    <input type="hidden" name="k_username" value="@Model.k_username" />
    <input type="hidden" name="k_password" value="@Model.k_password" />

    <label>Personel Id</label>
    @Html.TextBoxFor(p => p.k_id, new { @class = "form-control" })
    @Html.ValidationMessageFor(message => message.k_id, "", new { @disabled = "true", @class = "text-danger" })
    <hr />
    <label>Personel İsim Soyisim</label>
    @Html.TextBoxFor(p => p.k_isim, new { @class = "form-control" })
    @Html.ValidationMessageFor(message => message.k_isim, "", new { @class = "text-danger" })
    <hr />
    <label>Personel Tel</label>
    @Html.TextBoxFor(p => p.k_tel, new { @class = "form-control" })
    @Html.ValidationMessageFor(message => message.k_tel, "", new { @class = "text-danger" })
    <hr />
    <label>Personel Mail</label>
    @Html.TextBoxFor(p => p.k_mail, new { @class = "form-control" })
    @Html.ValidationMessageFor(message => message.k_mail, "", new { @class = "text-danger" })
    
    <hr />
    <label>Personel Baslangıc</label>
    @Html.TextBoxFor(p => p.k_baslangıc, new { @class = "form-control" })
    @Html.ValidationMessageFor(message => message.k_baslangıc, "", new { @class = "text-danger" })


</div>
<label>@ViewBag.uyarı</label>

    <div>

        <button class="btn btn-primary">Güncelle</button>
        <a href="/Adimn/Index" class="btn btn-primary">Geri Dön</a>
    </div>
}

stajproje2/Views/Güncelleme/Güncellesube.cshtml
@model stajproje2.Models.Subeler
@{
    ViewBag.Title = "Subegetir";
}

<h2>Subegetir</h2>
@using (Html.BeginForm("Güncellesube", "Güncelleme", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="from-group">
        <label>Sube Id</label>
        @Html.TextBoxFor(sub => sub.sube_id, new { @class = "form-control" })
        @Html.ValidationMessageFor(message => message.sube_id, "", new { @class = "text-danger" })
        <hr />
        <label>Sube Ad</label>
        @Html.TextBoxFor(sub => sub.sube_ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(message => message.sube_ad, "", new { @class = "text-danger" })
        <hr />
        <label>Sube İl</label>
        @Html.TextBoxFor(sub => sub.sube_il, new { @class = "form-control" })
        @Html.ValidationMessageFor(message => message.sube_il, "", new { @class = "text-danger" })
        <hr />
        <label>Sube Tel</label>
        @Html.TextBoxFor(sub => sub.sube_tel, new { @class = "form-control" })
        @Html.ValidationMessageFor(message => message.sube_tel, "", new { @class = "text-danger" })
        <hr />
        <label>Sube Adres</label>
        @Html.TextBoxFor(sub => sub.sube_adres, new { @class = "form-control" })
        @Html.ValidationMessageFor(message => message.sube_adres, "", new { @class = "text-danger" })
        <hr />



    </div>

    <div>

        <button class="btn btn-primary">Güncelle</button>
        <a href="/Adimn/Sube/" class="btn btn-primary" style="margin-left:10px">Geri Don</a>
    </div>
}

stajproje2/Views/Güncelleme/ZiyaretIslemleri.cshtml
@model stajproje2.Models.Ziyaretler
@{
    ViewBag.Title = "ZiyaretIslemleri";
}

<h2>ZiyaretIslemleri</h2>
<form class="form-group" method="post">
    @Html.AntiForgeryToken()

    <input type="hidden" name="z_id" value="@Model.z_id" />

    <label>Personel Seç</label>
    @Html.DropDownListFor(x => x.z_user_id, (List<SelectListItem>)ViewBag.ktgr, new { @class = "form-control", @name = "z_user_id" })
    @Html.ValidationMessageFor(message => message.z_user_id, "", new { @class = "text-danger" })


    <br />
    <label>Sube Secin</label>
    @Html.DropDownListFor(x => x.sube_fk_id, (List<SelectListItem>)ViewBag.sube, new { @class = "form-control", @name = "sube_fk_id" })
    @Html.ValidationMessageFor(message => message.sube_fk_id, "", new { @class = "text-danger" })
    <br />

    <label>Yapılacak İslem</label>
    @Html.DropDownListFor(x => x.z_olay_id, (List<SelectListItem>)ViewBag.olay, new { @class = "form-control", @name = "z_olay_id" })
    @Html.ValidationMessageFor(message => message.z_olay_id, "", new { @class = "text-danger" })
    <br />
    <label>Atanmış Tarih</label>
    @Html.TextBoxFor(x => x.z_tarih, new { @class = "form-control mr-2 mt-2", });

    <br />
    <label>Tarih Giriniz</label>
    <input type="datetime-local" name="z_tarihgüncel" class="form-control" />
    @Html.ValidationMessageFor(message => message.z_tarihgüncel, "", new { @class = "text-danger" })


    <button class="btn btn-info">Kaydet</button>
    <a href="/Adimn/Ziyaret/" class="btn btn-primary" style="margin-left:10px">>Geri Don</a>
</form>

stajproje2/Views/Güncelleme/Ziyraetata.cshtml
@model stajproje2.Models.Ziyaretler
@{
    ViewBag.Title = "ata";
}


<form class="form-group" method="post">
    @Html.AntiForgeryToken()
    <h2>Ziyaret Ata</h2>
    <br />
    <br />
    <br />
    <br />
    <br />

    <input type="hidden" name="z_resimm" />
    <input type="hidden" name="z_not" />
    <label>Ziyaret Ismi</label>

    <input type="text" name="z_ismi" class="form-control" />

    <label>Personel Seç</label>
    @Html.DropDownList("z_user_id", null, "", htmlAttributes: new { @class = "form-control mr-2 mt-2", })
    @Html.ValidationMessageFor(message => message.z_user_id, "", new { @class = "text-danger" })


    <br />
    <label>Sube Secin</label>
    @Html.DropDownList("sube_fk_id", null, "", htmlAttributes: new { @class = "form-control mr-2 mt-2", })
    @Html.ValidationMessageFor(message => message.sube_fk_id, "", new { @class = "text-danger" })
    <br />

    <br />
    <label>Tarih Giriniz</label>
    <input type="datetime-local" placeholder="2022-06-20" name="z_tarih" class="form-control" />
    @Html.ValidationMessageFor(message => message.z_tarih, "", new { @class = "text-danger" })


    <button class="btn btn-info">Kaydet</button>
    <a href="/Adimn/Ziyaret/" class="btn btn-primary" style="margin-left:10px">>Geri Don</a>
</form>